### ISSUE TITLE
[BUG] - vl-cookie-consent.min.js importeert niet vl-cookie-consent-opt-in.min.js

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-cookie-consent#41]
**Omschrijf het probleem**
_vl-cookie-consent.min.js_ gebruikt niet de minified _vl-cookie-consent-opt-in.**min**.js_ maar _vl-cookie-consent-opt-in.js_ waardoor wij volgende warnings krijgen:

> vl-form-label werd reeds gedefinieerd als custom element vl-core.min.js:115:35
> vl-form-validation-message werd reeds gedefinieerd als custom element vl-core.min.js:115:35
> vl-form-annotation werd reeds gedefinieerd als custom element vl-core.min.js:115:35
> vl-checkbox werd reeds gedefinieerd als custom element

Relevant stuk van vl-cookie-consent.min.js dat aantoont dat niet de minified versie wordt gebruikt:

`import{VlElement,define}from"/node_modules/vl-ui-core/dist/vl-core.min.js";import"/node_modules/vl-ui-button/dist/vl-button.min.js";import"/node_modules/vl-ui-form-grid/dist/vl-form-grid.min.js";import"/node_modules/vl-ui-modal/dist/vl-modal.min.js";import{analytics}from"/node_modules/vl-ui-cookie-consent/src/analytics.js";import"/node_modules/vl-ui-cookie-consent/dist/vl-cookie-consent-opt-in.js";export class ...`

**Gewenst gedrag**
Overal minified versie.

**Omgeving (gelieve aan te vullen):**
 - Versie component 4.0.1

**Comment by coemans** [comment]
Probleem zit op vl-ui-util niveau cfr. issue [#160](https://github.com/milieuinfo/webcomponent-vl-ui-util/issues/160).
