### ISSUE TITLE
[BUG] - style wordt niet altijd goed toegepast

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-ui-cookie-consent#43]
**Omschrijf het probleem**
In de niet-minified .js wordt de style niet in alle situaties goed toegepast. De minified js gebruiken lost het probleem op.
Het OMV team liep hier tegen bij hun gebruik van de vl-cookie-consent.

**Hoe te reproduceren**
Unminified .js gebruiken in de dist folder.

**Gewenst gedrag**
Style wordt ook bij niet-minified versie goed toegepast.

**Comment by coemans** [comment]
Vermoedelijk niet meer relevant, de kans dat OMV de CDN component gebruikt en niet de webcomponent lijkt me ook heel erg groot. Voorlopig sluit ik af zonder gevolg, maar aarzel niet om ticket opnieuw te openen als er alsnog problemen zouden zijn.
