### ISSUE TITLE
[BUG] - Cookie consent lijkt niet te werken in Microsoft Edge browser

### ISSUE THREAD

**Issue by koendecock** [milieuinfo/webcomponent-vl-ui-cookie-consent#56]
**Omschrijf het probleem**
De cookie consent lijkt niet tevoorschijn te komen. Ook de voorbeeldpagina https://webcomponenten.omgeving.vlaanderen.be/demo/vl-cookie-consent.html lijkt niet te werken in Microsoft Edge.

**Hoe te reproduceren**
Stappen om het probleem te reproduceren en indien mogelijks een code snippet: Open https://webcomponenten.omgeving.vlaanderen.be/demo/vl-cookie-consent.html met Microsoft Edge browser en je ziet al meteen dat de pagina niet laadt zoals dat de bedoeling is. Enkel de knoppen zijn zichtbaar, geen tekst ertussen. Klik nu op de cookie consent knoppen. Er gebeurt niets.

**Screenshots**
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/2820926/86091075-929a9680-baab-11ea-9525-c650bfdc6a9a.png">
**Omgeving (gelieve aan te vullen):**
 - Browser Microsoft Edge
 - Versie  44.17763.1.0
 - Versie component 4.0.2

**Comment by coemans** [comment]
@koendecock het probleem is nu niet (meer) reproduceerbaar op de LATEST versie van Microsoft Edge. Ik sluit hierdoor ticket af, maar aarzel zeker niet om aan te geven indien het alsnog niet zou werken op een specifieke versie die voor jullie nodig blijkt te zijn.
