### ISSUE TITLE
[BUG] - Cookie consent openen in chrome (zonder dat het in de demo pagina zit) geeft vaak een modal zonder tekst

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-cookie-consent#57]
**Omschrijf het probleem**
In chrome gebeurt de rendering niet consistent voor de cookie-consent.
Als er enkel de cookie consent wordt gebruikt (zonder gebruik van de demo pagina) wordt er vaak geen tekst getoond in de modal. Soms komt de css er wel door. Mogelijk ergens een css race conditie. Na enkele keren refreshen komt er al wat meer tekst door.
Na een window resize is het wel in orde.
Ook moet de css van button/form-grid/modal ingeladen worden of de stijl zit niet goed (probleem met slotted content?). Ik zou verwachten dat dit niet moet.

**Hoe te reproduceren**
Zie branch: https://github.com/milieuinfo/webcomponent-vl-ui-cookie-consent/tree/bug_geen_tekst_in_chrome 
demo/vl-cookie-consent.geen_tekst_in_chrome.html

**Gewenst gedrag**
Tekst wordt getoond

**Screenshots**
![image](https://user-images.githubusercontent.com/28813026/86469895-9f80e980-bd3a-11ea-9e1b-49df05e5bd05.png)
![image](https://user-images.githubusercontent.com/28813026/86470118-11f1c980-bd3b-11ea-8e38-3ae094b5448f.png)

**Omgeving (gelieve aan te vullen):**
 - Browser: ENKEL Chrome
 - Versie: Versie 83.0.4103.116 (Officiële build) (64-bits)

**Extra info**
Ik had eens geprobeerd de content slot in een aparte shadow dom te steken en toen was er al iets meer te zien, maar gaf dan weer andere problemen.

**Comment by coemans** [comment]
@Pieter-Beckers ik kan het probleem niet meer reproduceren, jij nog wel?

**Comment by Pieter-Beckers** [comment]
@coemans Heb het nog eens proberen reproduceren, maar ik kreeg de cookie-consent niet aan de praat zonder demo pagina en zonder `data-vl-auto-open-disabled` + button => normaal zou ik verwachten dat die dan direct opent, maar dit lijkt niet zo te zijn

**Comment by coemans** [comment]
@Pieter-Beckers zou het kunnen dat je lokaal nog een cookie had waardoor hij niet opende? Bij het sluiten van de consent modal, wordt een cookie gezet zodat volgende keer de consent niet meer geopend wordt omdat de gebruiker al bevestigd heeft.
